=== cupteanacious/DeCoRe/DCR/DCR.DCRGraph/dcr-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "events": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "initiator": {
                            "type": "string"
                        },
                        "action": {
                            "type": "string"
                        },
                        "receivers": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    },
                    "required": [
                        "id",
                        "initiator",
                        "action",
                        "receivers"
                    ],
                    "additionalProperties": false
                }
        },
        "nestings": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "events": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "childNestings":  {"$ref": "#/properties/nestings"}
                        
                    },
                    "required": [
                        "id",
                        "events",
                        "childNestings"
                    ],
                    "additionalProperties": false
                }
        },
        "relationships": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "from": {
                            "type": "string"
                        },
                        "to": {
                            "type": "string"
                        },
                        "relations": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "relationType": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "relationType"
                                    ],
                                    "additionalProperties": false
                                }
                            ]
                        }
                    },
                    "required": [
                        "from",
                        "to",
                        "relations"
                    ],
                    "additionalProperties": false
                }
        },
        "markings": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "eventId": {
                            "type": "string"
                        },
                        "marking": {
                            "type": "object",
                            "properties": {
                                "executed": {
                                    "type": "boolean"
                                },
                                "included": {
                                    "type": "boolean"
                                },
                                "pending": {
                                    "type": "boolean"
                                }
                            },
                            "required": [
                                "executed",
                                "included",
                                "pending"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "eventId",
                        "marking"
                    ],
                    "additionalProperties": false
                }
        }
    },
    "required": [
        "events",
        "nestings",
        "relationships",
        "markings"
    ],
    "additionalProperties": false
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/true/ePResponseEPPMilestoneE.json
{
    "events": [
        {
            "id": "ePResponseePP",
            "initiator": "eP",
            "action": "Response",
            "receivers": [
                "ePP"
            ]
        },
        {
            "id": "ePPMilestonee",
            "initiator": "ePP",
            "action": "Milestone",
            "receivers": [
                "e"
            ]
        },
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [
        {
            "from": "ePResponseePP",
            "to": "ePPMilestonee",
            "relations": [
                {
                    "relationType": "Response"
                }
            ]
        },
        {
            "from": "ePPMilestonee",
            "to": "eNullNull",
            "relations": [
                {
                    "relationType": "Milestone"
                }
            ]
        }
    ],
    "markings": [
        {
            "eventId": "ePResponseePP",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "ePPMilestonee",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/true/ePMilestoneE.json
{
    "events": [
        {
            "id": "ePMilestonee",
            "initiator": "eP",
            "action": "Milestone",
            "receivers": [
                "e"
            ]
        },
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [
        {
            "from": "ePMilestonee",
            "to": "eNullNull",
            "relations": [
                {
                    "relationType": "Milestone"
                }
            ]
        }
    ],
    "markings": [
        {
            "eventId": "ePMilestonee",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}
