=== cupteanacious/DeCoRe/DCR/DCR.DCRGraph/dcr-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "events": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "initiator": {
                            "type": "string"
                        },
                        "action": {
                            "type": "string"
                        },
                        "receivers": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    },
                    "required": [
                        "id",
                        "initiator",
                        "action",
                        "receivers"
                    ],
                    "additionalProperties": false
                }
        },
        "nestings": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "events": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "childNestings":  {"$ref": "#/properties/nestings"}
                        
                    },
                    "required": [
                        "id",
                        "events",
                        "childNestings"
                    ],
                    "additionalProperties": false
                }
        },
        "relationships": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "from": {
                            "type": "string"
                        },
                        "to": {
                            "type": "string"
                        },
                        "relations": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "relationType": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "relationType"
                                    ],
                                    "additionalProperties": false
                                }
                            ]
                        }
                    },
                    "required": [
                        "from",
                        "to",
                        "relations"
                    ],
                    "additionalProperties": false
                }
        },
        "markings": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "eventId": {
                            "type": "string"
                        },
                        "marking": {
                            "type": "object",
                            "properties": {
                                "executed": {
                                    "type": "boolean"
                                },
                                "included": {
                                    "type": "boolean"
                                },
                                "pending": {
                                    "type": "boolean"
                                }
                            },
                            "required": [
                                "executed",
                                "included",
                                "pending"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "eventId",
                        "marking"
                    ],
                    "additionalProperties": false
                }
        }
    },
    "required": [
        "events",
        "nestings",
        "relationships",
        "markings"
    ],
    "additionalProperties": false
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/true/ePIncludeEPPConditionE.json
{
    "events": [
        {
            "id": "ePIncludeePP",
            "initiator": "eP",
            "action": "Include",
            "receivers": [
                "ePP"
            ]
        },
        {
            "id": "ePPConditione",
            "initiator": "ePP",
            "action": "Condition",
            "receivers": [
                "e"
            ]
        },
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [
        {
            "from": "ePIncludeePP",
            "to": "ePPConditione",
            "relations": [
                {
                    "relationType": "Inclusion"
                }
            ]
        },
        {
            "from": "ePPConditione",
            "to": "eNullNull",
            "relations": [
                {
                    "relationType": "Condition"
                }
            ]
        }
    ],
    "markings": [
        {
            "eventId": "ePIncludeePP",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "ePPConditione",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/true/eIsEP.json
{
    "events": [
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [],
    "markings": [
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}

=== cupteanacious/DeCoRe/DCR/DCR.CLI/examples/TeamleaderWorkersManagement-epp.json
{"events":[{"id":"WorkerBHandleTaskTeamLeader","initiator":"WorkerB","action":"HandleTask","receivers":["TeamLeader"]},{"id":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","initiator":"TeamLeader","action":"GiveTasks","receivers":["WorkerA","WorkerB","WorkerC"]},{"id":"WorkerCHandleJobTeamLeader","initiator":"WorkerC","action":"HandleJob","receivers":["TeamLeader"]},{"id":"WorkerAHandleTaskTeamLeaderWorkerB","initiator":"WorkerA","action":"HandleTask","receivers":["TeamLeader","WorkerB"]},{"id":"ManagementPrioritizeWorkerAWorkerAWorkerB","initiator":"Management","action":"PrioritizeWorkerA","receivers":["WorkerA","WorkerB"]},{"id":"WorkerCCallSickTeamLeader","initiator":"WorkerC","action":"CallSick","receivers":["TeamLeader"]}],"nestings":[],"relationships":[{"from":"ManagementPrioritizeWorkerAWorkerAWorkerB","to":"WorkerAHandleTaskTeamLeaderWorkerB","relations":[{"relationType":"Response"}]},{"from":"WorkerAHandleTaskTeamLeaderWorkerB","to":"WorkerBHandleTaskTeamLeader","relations":[{"relationType":"Milestone"}]},{"from":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","to":"WorkerBHandleTaskTeamLeader","relations":[{"relationType":"Condition"}]},{"from":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","to":"WorkerCHandleJobTeamLeader","relations":[{"relationType":"Condition"}]},{"from":"WorkerCCallSickTeamLeader","to":"WorkerCHandleJobTeamLeader","relations":[{"relationType":"Exclusion"}]},{"from":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","to":"WorkerAHandleTaskTeamLeaderWorkerB","relations":[{"relationType":"Condition"}]}],"markings":[{"eventId":"WorkerBHandleTaskTeamLeader","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"WorkerCHandleJobTeamLeader","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"WorkerAHandleTaskTeamLeaderWorkerB","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"ManagementPrioritizeWorkerAWorkerAWorkerB","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"WorkerCCallSickTeamLeader","marking":{"executed":false,"included":true,"pending":false}}]}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/true/ePInclusionE.json
{
    "events": [
        {
            "id": "ePInclusione",
            "initiator": "eP",
            "action": "Inclusion",
            "receivers": [
                "e"
            ]
        },
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [
        {
            "from": "ePInclusione",
            "to": "eNullNull",
            "relations": [
                {
                    "relationType": "Inclusion"
                }
            ]
        }
    ],
    "markings": [
        {
            "eventId": "ePInclusione",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/true/ePConditionE.json
{
    "events": [
        {
            "id": "ePConditione",
            "initiator": "eP",
            "action": "Condition",
            "receivers": [
                "e"
            ]
        },
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [
        {
            "from": "ePConditione",
            "to": "eNullNull",
            "relations": [
                {
                    "relationType": "Condition"
                }
            ]
        }
    ],
    "markings": [
        {
            "eventId": "ePConditione",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/execution/Action1ExcludesItself.json
{
  "events": [
    {
      "id": "AAction1B",
      "initiator": "A",
      "action": "Action1",
      "receivers": ["B"]
    }
  ],
  "nestings": [],
  "relationships": [
    {
      "from": "AAction1B",
      "to": "AAction1B",
      "relations": [{ "relationType": "Exclusion" }]
    }
  ],
  "markings": [
    {
      "eventId": "AAction1B",
      "marking": { "executed": false, "included": true, "pending": false }
    }
  ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/true/ePExclusionE.json
{
    "events": [
        {
            "id": "ePExclusione",
            "initiator": "eP",
            "action": "Exclusion",
            "receivers": [
                "e"
            ]
        },
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [
        {
            "from": "ePExclusione",
            "to": "eNullNull",
            "relations": [
                {
                    "relationType": "Exclusion"
                }
            ]
        }
    ],
    "markings": [
        {
            "eventId": "ePExclusione",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/execution/Action1MakesAction2Pending.json
{
  "events": [
    {
      "id": "AAction1B",
      "initiator": "A",
      "action": "Action1",
      "receivers": ["B"]
    },
    {
      "id": "AAction2B",
      "initiator": "A",
      "action": "Action2",
      "receivers": ["B"]
    }
  ],
  "nestings": [],
  "relationships": [
    {
      "from": "AAction1B",
      "to": "AAction2B",
      "relations": [{ "relationType": "Response" }]
    }
  ],
  "markings": [
    {
      "eventId": "AAction1B",
      "marking": { "executed": false, "included": true, "pending": false }
    },
    {
      "eventId": "AAction2B",
      "marking": { "executed": false, "included": true, "pending": false }
    }
  ]
}
