=== cupteanacious/DeCoRe/DCR/DCR.DCRGraph/dcr-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "events": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "initiator": {
                            "type": "string"
                        },
                        "action": {
                            "type": "string"
                        },
                        "receivers": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    },
                    "required": [
                        "id",
                        "initiator",
                        "action",
                        "receivers"
                    ],
                    "additionalProperties": false
                }
        },
        "nestings": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "events": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "childNestings":  {"$ref": "#/properties/nestings"}
                        
                    },
                    "required": [
                        "id",
                        "events",
                        "childNestings"
                    ],
                    "additionalProperties": false
                }
        },
        "relationships": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "from": {
                            "type": "string"
                        },
                        "to": {
                            "type": "string"
                        },
                        "relations": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "relationType": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "relationType"
                                    ],
                                    "additionalProperties": false
                                }
                            ]
                        }
                    },
                    "required": [
                        "from",
                        "to",
                        "relations"
                    ],
                    "additionalProperties": false
                }
        },
        "markings": {
            "type": "array",
            "items":
                {
                    "type": "object",
                    "properties": {
                        "eventId": {
                            "type": "string"
                        },
                        "marking": {
                            "type": "object",
                            "properties": {
                                "executed": {
                                    "type": "boolean"
                                },
                                "included": {
                                    "type": "boolean"
                                },
                                "pending": {
                                    "type": "boolean"
                                }
                            },
                            "required": [
                                "executed",
                                "included",
                                "pending"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "eventId",
                        "marking"
                    ],
                    "additionalProperties": false
                }
        }
    },
    "required": [
        "events",
        "nestings",
        "relationships",
        "markings"
    ],
    "additionalProperties": false
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/deadlocks/example1.json
{
  "events": [
    {
      "id": "B2A",
      "initiator": "B",
      "action": "2",
      "receivers": [ "A", "C" ]
    },
    {
      "id": "C3B",
      "initiator": "C",
      "action": "3",
      "receivers": [ "B", "A" ]
    },
    {
      "id": "A1B",
      "initiator": "A",
      "action": "1",
      "receivers": [ "B", "C" ]
    }
  ],
  "nestings": [],
  "relationships": [
    {
      "from": "C3B",
      "to": "C3B",
      "relations": [ { "relationType": "Exclusion" } ]
    },
    {
      "from": "C3B",
      "to": "B2A",
      "relations": [ { "relationType": "Exclusion" } ]
    },
    {
      "from": "B2A",
      "to": "A1B",
      "relations": [ { "relationType": "Exclusion" } ]
    },
    {
      "from": "A1B",
      "to": "A1B",
      "relations": [ { "relationType": "Condition" } ]
    }
  ],
  "markings": [
    {
      "eventId": "B2A",
      "marking": {
        "executed": false,
        "included": true,
        "pending": false
      }
    },
    {
      "eventId": "C3B",
      "marking": {
        "executed": false,
        "included": true,
        "pending": true
      }
    },
    {
      "eventId": "A1B",
      "marking": {
        "executed": false,
        "included": true,
        "pending": true
      }
    }
  ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/true/ePResponseE.json
{
    "events": [
        {
            "id": "ePResponsee",
            "initiator": "eP",
            "action": "Response",
            "receivers": [
                "e"
            ]
        },
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [
        {
            "from": "ePResponsee",
            "to": "eNullNull",
            "relations": [
                {
                    "relationType": "Response"
                }
            ]
        }
    ],
    "markings": [
        {
            "eventId": "ePResponsee",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/endpointprojectable/graph.json
{"events":[{"id":"R1AR2","initiator":"R1","action":"A","receivers":["R2"]},{"id":"R3A2R4","initiator":"R3","action":"A2","receivers":["R4"]}],"nestings":[{"id":"Nesting1","events":["R1AR2","R3A2R4"],"childNestings":[]}],"relationships":[],"markings":[{"eventId":"R1AR2","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"R3A2R4","marking":{"executed":false,"included":true,"pending":false}}]}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/deadlocks/e2ro3re2.json
{"events":[{"id":"RoleA64a59094RoleB","initiator":"RoleA","action":"64a59094","receivers":["RoleB"]},{"id":"RoleA57aa8121RoleB","initiator":"RoleA","action":"57aa8121","receivers":["RoleB"]},{"id":"RoleB5f383aa5RoleC","initiator":"RoleB","action":"5f383aa5","receivers":["RoleC"]},{"id":"RoleB2f76a7d0RoleC","initiator":"RoleB","action":"2f76a7d0","receivers":["RoleC"]}],"nestings":[],"relationships":[{"from":"RoleA64a59094RoleB","to":"RoleB5f383aa5RoleC","relations":[{"relationType":"Exclusion"}]},{"from":"RoleA64a59094RoleB","to":"RoleB5f383aa5RoleC","relations":[{"relationType":"Milestone"}]},{"from":"RoleA57aa8121RoleB","to":"RoleB5f383aa5RoleC","relations":[{"relationType":"Inclusion"}]},{"from":"RoleA57aa8121RoleB","to":"RoleB5f383aa5RoleC","relations":[{"relationType":"Exclusion"}]},{"from":"RoleB5f383aa5RoleC","to":"RoleB2f76a7d0RoleC","relations":[{"relationType":"Condition"}]},{"from":"RoleB5f383aa5RoleC","to":"RoleB2f76a7d0RoleC","relations":[{"relationType":"Milestone"}]}],"markings":[]}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/deadlocks/example2.json
{
  "events": [
    {
      "id": "A1B",
      "initiator": "A",
      "action": "1",
      "receivers": [
        "B"
      ]
    },
    {
      "id": "B2A",
      "initiator": "B",
      "action": "2",
      "receivers": [
        "A"
      ]
    },
    {
      "id": "C3B",
      "initiator": "C",
      "action": "3",
      "receivers": [
        "B"
      ]
    },
    {
      "id": "DMakePendingCB",
      "initiator": "D",
      "action": "MakePending",
      "receivers": [
        "C",
        "B"
      ]
    }
  ],
  "nestings": [
  ],
  "relationships": [
    {
      "from": "C3B",
      "to": "C3B",
      "relations": [
        {
          "relationType": "Exclusion"
        }
      ]
    },
    {
      "from": "C3B",
      "to": "B2A",
      "relations": [
        {
          "relationType": "Exclusion"
        }
      ]
    },
    {
      "from": "B2A",
      "to": "A1B",
      "relations": [
        {
          "relationType": "Exclusion"
        }
      ]
    },
    {
      "from": "A1B",
      "to": "A1B",
      "relations": [
        {
          "relationType": "Condition"
        }
      ]
    },
    {
      "from": "DMakePendingCB",
      "to": "A1B",
      "relations": [
        {
          "relationType": "Response"
        }
      ]
    },
    {
      "from": "DMakePendingCB",
      "to": "C3B",
      "relations": [
        {
          "relationType": "Response"
        }
      ]
    }
  ],
  "markings": [
    {
      "eventId": "A1B",
      "marking": {
        "executed": false,
        "included": true,
        "pending": false
      }
    },
    {
      "eventId": "B2A",
      "marking": {
        "executed": false,
        "included": true,
        "pending": false
      }
    },
    {
      "eventId": "C3B",
      "marking": {
        "executed": false,
        "included": true,
        "pending": false
      }
    },
    {
      "eventId": "DMakePendingCB",
      "marking": {
        "executed": false,
        "included": true,
        "pending": false
      }
    }
  ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/dependencies/false/ePMilestoneEPPMilestoneE.json
{
    "events": [
        {
            "id": "ePMilestoneePP",
            "initiator": "eP",
            "action": "Milestone",
            "receivers": [
                "ePP"
            ]
        },
        {
            "id": "ePPMilestonee",
            "initiator": "ePP",
            "action": "Milestone",
            "receivers": [
                "e"
            ]
        },
        {
            "id": "eNullNull",
            "initiator": "e",
            "action": "Null",
            "receivers": [
                "Null"
            ]
        }
    ],
    "nestings": [],
    "relationships": [
        {
            "from": "ePMilestoneePP",
            "to": "ePPMilestonee",
            "relations": [
                {
                    "relationType": "Milestone"
                }
            ]
        },
        {
            "from": "ePPMilestonee",
            "to": "eNullNull",
            "relations": [
                {
                    "relationType": "Milestone"
                }
            ]
        }
    ],
    "markings": [
        {
            "eventId": "ePMilestoneePP",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "ePPMilestonee",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        },
        {
            "eventId": "eNullNull",
            "marking": {
                "executed": false,
                "included": true,
                "pending": false
            }
        }
    ]
}

=== cupteanacious/DeCoRe/DCR/DCR.Tests/graphs/deadlocks/example3.json
{
  "events": [
    {
      "id": "A1B",
      "initiator": "A",
      "action": "1",
      "receivers": [
        "B"
      ]
    },
    {
      "id": "B2A",
      "initiator": "B",
      "action": "2",
      "receivers": [
        "A"
      ]
    }
  ],
  "nestings": [
  ],
  "relationships": [
    {
      "from": "A1B",
      "to": "B2A",
      "relations": [
        {
          "relationType": "Condition"
        }
      ]
    },
    {
      "from": "B2A",
      "to": "A1B",
      "relations": [
        {
          "relationType": "Condition"
        }
      ]
    }
  ],
  "markings": [
    {
      "eventId": "A1B",
      "marking": {
        "executed": false,
        "included": true,
        "pending": true
      }
    },
    {
      "eventId": "B2A",
      "marking": {
        "executed": false,
        "included": true,
        "pending": false
      }
    }
  ]
}

=== cupteanacious/DeCoRe/DCR/DCR.CLI/examples/TeamleaderWorkersManagement-not-epp.json
{"events":[{"id":"WorkerBHandleTaskTeamLeader","initiator":"WorkerB","action":"HandleTask","receivers":["TeamLeader"]},{"id":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","initiator":"TeamLeader","action":"GiveTasks","receivers":["WorkerA","WorkerB","WorkerC"]},{"id":"WorkerCHandleJobTeamLeader","initiator":"WorkerC","action":"HandleJob","receivers":["TeamLeader"]},{"id":"WorkerAHandleTaskTeamLeader","initiator":"WorkerA","action":"HandleTask","receivers":["TeamLeader"]},{"id":"ManagementPrioritizeWorkerAWorkerA","initiator":"Management","action":"PrioritizeWorkerA","receivers":["WorkerA"]},{"id":"WorkerCCallSickTeamLeader","initiator":"WorkerC","action":"CallSick","receivers":["TeamLeader"]}],"nestings":[],"relationships":[{"from":"ManagementPrioritizeWorkerAWorkerA","to":"WorkerAHandleTaskTeamLeader","relations":[{"relationType":"Response"}]},{"from":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","to":"WorkerAHandleTaskTeamLeader","relations":[{"relationType":"Condition"}]},{"from":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","to":"WorkerBHandleTaskTeamLeader","relations":[{"relationType":"Condition"}]},{"from":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","to":"WorkerCHandleJobTeamLeader","relations":[{"relationType":"Condition"}]},{"from":"WorkerCCallSickTeamLeader","to":"WorkerCHandleJobTeamLeader","relations":[{"relationType":"Exclusion"}]},{"from":"WorkerAHandleTaskTeamLeader","to":"WorkerBHandleTaskTeamLeader","relations":[{"relationType":"Milestone"}]}],"markings":[{"eventId":"WorkerBHandleTaskTeamLeader","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"TeamLeaderGiveTasksWorkerAWorkerBWorkerC","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"WorkerCHandleJobTeamLeader","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"WorkerAHandleTaskTeamLeader","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"ManagementPrioritizeWorkerAWorkerA","marking":{"executed":false,"included":true,"pending":false}},{"eventId":"WorkerCCallSickTeamLeader","marking":{"executed":false,"included":true,"pending":false}}]}
